---

  name: code style

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  jobs:
    build:

      runs-on: ubuntu-latest

      continue-on-error: true
      strategy:
        matrix:
          python-version: ['3.10', '3.11']

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies on Python ${{ matrix.python-version }}
          run: |
            python -m pip install --upgrade pip
            pip install wemake-python-styleguide flake8-html mypy lxml pytest types-requests

        - name: Run Flake8
          id: run_linters
          run: flake8
              --config=setup.cfg
              --exclude=form_api/tests/
              --format=html
              --htmldir=flake8-report .
          continue-on-error: true

        - name: Run MyPy
          id: run_mypy
          run: |
              mkdir mypy-report && \
              mypy --config-file ./setup.cfg \
              --exclude "^tests$|^form_api/tests/" \
              --show-error-codes \
              --html-report mypy-report .
          continue-on-error: true

        - name: Save mypy HTML report
          uses: actions/upload-artifact@v3
          continue-on-error: true
          if: ${{ steps.run_mypy.outcome == 'failure' }}
          with:
            name: mypy-report_${{ matrix.python-version }}
            path: mypy-report/

        - name: Save flake8 HTML report
          uses: actions/upload-artifact@v3
          continue-on-error: true
          if: ${{ steps.run_linters.outcome == 'failure' }}
          with:
            name: flake-report_${{ matrix.python-version }}
            path: flake8-report/
